on:
  push:
    branches: [main]

jobs:
  revision:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener archivos del repositorio
        uses: actions/checkout@v3

      - name: Verificar existencia de archivos obligatorios
        run: |
          if [ ! -f index.html ]; then echo "ERROR: Falta index.html"; exit 1; fi
          if [ ! -f estilo.css ]; then echo "ERROR: Falta estilo.css"; exit 1; fi

      - name: W3C HTML Validator
        uses: center-key/w3c-html-validator@v1.1.0
        with:
           files: index.html
          
      - name: Preparar archivos para publicación
        run: |
            mkdir publicacion
            cp *.html *.css publicacion/

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./publicacion
